
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Radiobutton, IntVar, StringVar, OptionMenu, ttk


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\ASUS\Downloads\Tkinter-Designer-master\Tkinter-Designer-master\Page2\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


class Layer():
    def __init__(self, window, canvas, layer, args):
        self.window = window
        self.canvas = canvas
        self.layer = layer
        self.args = args
        self.index = 0
        self.name = ''
        self.layer_var = StringVar()
        def update(*args):
            self.name = self.layer_var.get()
        self.layer_var.trace_add("write", update)
        
    def create_layer(self):
        self.canvas.create_text( 80.0,
                            269.0,
                            anchor="nw",
                            text=str(self.index+1)+'.',
                            fill="#000000",
                            font=("Inter", 12 * -1))
        layer = ttk.Combobox(self.window, values=self.layer, width=10, textvariable=self.layer_var)
        self.canvas.create_window(
            127.0,
            269.0,
            window=layer
        )

        arg = ttk.Combobox(self.window, values=self.args, width=7)
        self.canvas.create_window(
            125.0,
            304.0,
            window=arg
        )

        self.canvas.create_text( 204.0,
                            304.0,
                            anchor="nw",
                            text="=",
                            fill="#000000",
                            font=("Inter", 12 * -1))
        
        textbox = Entry(
            bd=0,
            bg="#FFFFFF",
            fg="#000716",
            highlightthickness=0
        )
        self.canvas.create_window(
            223.0,
            304.0,
            width=80.0,
            height=16.0,
            window=textbox
        )

    def layer_val(self):
        return self.layer_var.get()

    def add_argument(self):
        pass

    def remove_argument(self):
        pass

    def remove_layer(self):
        pass

window = Tk()

window.geometry("670x423")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 423,
    width = 670,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge",
    scrollregion = (0,0,2000,5000)
)

canvas.place(x = 0, y = 0)

# # mousewheel scrolling 
canvas.bind('<MouseWheel>', lambda event: canvas.yview_scroll(-int(event.delta / 60), "units"))
# scrollbar 
scrollbar = ttk.Scrollbar(window, orient = 'vertical', command = canvas.yview)
canvas.configure(yscrollcommand = scrollbar.set)
scrollbar.place(relx = 1, rely = 0, relheight = 1, anchor = 'ne')
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
app_name = canvas.create_image(
    335.0,
    34.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
gpu_lim = canvas.create_image(
    330.70001220703125,
    96.51399993896484,
    image=image_image_2
)

# Add radio buttons
radio_var = IntVar()
radio_button_1 = Radiobutton(
    window,
    text="Yes",
    variable=radio_var,
    value=True,
    bg="#FFFFFF",
    selectcolor="#FFFFFF",
    font=("Arial", 8)
)
canvas.create_window(
    280,
    120,
    window=radio_button_1
)
radio_button_2 = Radiobutton(
    window,
    text="No",
    variable=radio_var,
    value=False,
    bg="#FFFFFF",
    selectcolor="#FFFFFF",
    font=("Arial", 8)
)
canvas.create_window(
    380,
    120,
    window=radio_button_2
)
lim = 0
def print_selection():
    global lim
    lim = radio_var.get()
    print(lim)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
md_config = canvas.create_image(
    333.9100036621094,
    141.5,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
md_label = canvas.create_image(
    112.91000366210938,
    172.51400756835938,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
md_type = canvas.create_image(
    335.0,
    174.0,
    image=image_image_5
)


'''canvas.create_text(
    80.0,
    212.0,
    anchor="nw",
    text="Layers:",
    fill="#000000",
    font=("Italiana Regular", 14 * -1)
)

canvas.create_text(
    127.0,
    268.0,
    anchor="nw",
    text="Conv2D()\n\n",
    fill="#000000",
    font=("Inter", 12 * -1)
)

canvas.create_text(
    125.0,
    304.0,
    anchor="nw",
    text="kernel_size\n",
    fill="#000000",
    font=("Inter", 12 * -1)
)

textbox = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
textbox.place(
    x=223.0,
    y=304.0,
    width=80.0,
    height=16.0
)'''
layer = ['a', 'b', 'c', 'd', 'e', 'f']
args = ['1', '2', '3', '4', '5']
a = Layer(window, canvas, layer, args)
a.create_layer()
name = a.layer_val()
button_add_layer = PhotoImage(
    file=relative_to_assets("button_2.png"))
add_layer_btn = Button(
    image=button_add_layer,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("add_layer_btn clicked"),
    relief="flat"
)
canvas.create_window(
    119.0,
    341.0,
    width=84.0,
    height=17.0,
    window=add_layer_btn
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_rm = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
canvas.create_window(
    210.0,
    268.0,
    width=76.0,
    height=13.0,
    window=button_rm
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_add_arg = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
canvas.create_window(
    304.0,
    307.0,
    width=77.0,
    height=11.0,
    window=button_add_arg
)

'''canvas.create_text(
    204.0,
    304.0,
    anchor="nw",
    text="=",
    fill="#000000",
    font=("Inter", 12 * -1)
)'''

button_ok = PhotoImage(
    file=relative_to_assets("button_1.png"))
ok_btn = Button(
    image=button_ok,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print(a.name+' ngu vcl djt con me may'),
    relief="flat"
)
canvas.create_window(
    283.0,
    380.0,
    width=104.0,
    height=37.0,
    anchor='nw',
    window=ok_btn
)

window.resizable(False, False)
window.mainloop()
